version: "2"
run:
  concurrency: 4
  issues-exit-code: 1
  tests: false
linters:
  default: all
  disable:
    - depguard
    - dupl
    - dupword
    - exhaustive
    - exhaustruct
    - gochecknoglobals
    - godot
    - godox
    - ireturn
    - lll
    - mnd
    - nilnil
    - nolintlint
    - nonamedreturns
    - revive
    - tagliatelle
    - wrapcheck
    - wsl
    - noinlineerr
    - unparam
    - testpackage
    - interfacebloat
  settings:
    cyclop:
      max-complexity: 25
      package-average: 0
    dupl:
      threshold: 150
    errcheck:
      check-type-assertions: true
      check-blank: true
    exhaustive:
      default-signifies-exhaustive: true
    funlen:
      lines: 500
      statements: 400
    nestif:
      min-complexity: 10
    goconst:
      min-len: 3
      min-occurrences: 3
    gocognit:
      min-complexity: 40
    lll:
      line-length: 140
    misspell:
      locale: US
    nakedret:
      max-func-lines: 30
    prealloc:
      simple: true
      range-loops: true
      for-loops: false
    unparam:
      check-exported: true
    varnamelen:
      max-distance: 5
      min-name-length: 3
      check-receiver: false
      check-return: false
      ignore-names:
        - err
        - fn
        - ch
        - id
        - db
        - w
        - r
        - tx
        - ok
        - i
        - j
        - wg
        - cb
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - unparam
        path: src/internal/storage/memory
      - linters:
          - interfacer
        path: src/cmd
      - path: (.+)\.go$
        text: should have comment or be unexported
    paths:
      - src/internal/generated
      - pkg/gen
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
    gofmt:
      simplify: true
    gofumpt:
      extra-rules: false
      module-path: stagen
  exclusions:
    generated: lax
    paths:
      - src/internal/generated
      - pkg/gen
      - third_party$
      - builtin$
      - examples$
